### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by bmfay** [HashNuke/heroku-buildpack-elixir#132] opened 2018-09-19 17:24 UTC
I am encountering the following error on our latest build:

```
2018-09-19T16:18:50.509158+00:00 heroku[web.1]: Starting process with command `mix phoenix.server`
2018-09-19T16:18:43+00:00 app[heroku-postgres]: source=HEROKU_POSTGRESQL_PINK addon=postgresql-parallel-25439 sample#current_transaction=295524 sample#db_size=1432679911bytes sample#tables=64 sample#active-connections=8 sample#waiting-connections=0 sample#index-cache-hit-rate=0.99936 sample#table-cache-hit-rate=0.99422 sample#load-avg-1m=0 sample#load-avg-5m=0 sample#load-avg-15m=0 sample#read-iops=0 sample#write-iops=0.008781 sample#memory-total=4044884kB sample#memory-free=194984kB sample#memory-cached=3230360kB sample#memory-postgres=21532kB
2018-09-19T16:19:51.093245+00:00 heroku[web.1]: State changed from starting to crashed
2018-09-19T16:19:51.095163+00:00 heroku[web.1]: State changed from crashed to starting
2018-09-19T16:19:50.921000+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-09-19T16:19:50.921186+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-09-19T16:19:51.066559+00:00 heroku[web.1]: Process exited with status 137
```

I am quite stumped by this as even when rolling back to the previous commit which had deployed flawlessly, I see the same error.    Nothing has changed with respect to configuration.  Any ideas?  

(Elixir 1.2 / Phoenix 1.2.5)

**Comment by nezcich** [comment] 2018-11-13 20:47
Solution?

**Comment by nezcich** [comment] 2018-11-13 20:48
Solution?

**Comment by bmfay** [comment] 2019-01-05 23:45
@nezcich sorry for the delay in response.  I never found a solution, it just mysteriously started working again.  Now I've encountered it again and, again, have no idea how to resolve it and so I am re-opening this.

**Comment by bmfay** [comment] 2019-01-05 23:54
@nezcich I just kept redeploying until it worked.  Really no clue what's going on.  Others discussing this issue elsewhere have suggested adding

```
http: [port: {:system, "PORT"}]
```

to the config, which resolved it for some, but I already had that in place and still encounter this issue from time to time.

**Comment by HashNuke** [comment] 2019-04-27 12:15
@bmfay Closing this issue since it has been resolved.
IF not, please do feel free to share any details to reproduce this issue and we will look into it.

**Closed by HashNuke** 2019-04-27 12:15 UTC

**Comment by mauricionr** [comment] 2019-09-12 02:39
> @nezcich I just kept redeploying until it worked. Really no clue what's going on. Others discussing this issue elsewhere have suggested adding
> 
> ```
> http: [port: {:system, "PORT"}]
> ```
> 
> to the config, which resolved it for some, but I already had that in place and still encounter this issue from time to time.

this works for me, thanks
