### ISSUE TITLE
Too many levels of symbolic links

### ISSUE THREAD

**Issue by philipbrown** [HashNuke/heroku-buildpack-elixir#183] opened 2020-11-25 09:05 UTC
Hi,

I'm getting the following error when compiling the buildpack:
```
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack heroku-18
       * Erlang 23.1.2
       * Elixir v1.11.2 
-----> Using cached Erlang 23.1.2
-----> Installing Erlang 23.1.2 
/tmp/buildpacks/f4df38e3253cd41bc07092e4796127c7776a7e7f/lib/erlang_funcs.sh: line 39: /app/.platform_tools/erlang/Install: Too many levels of symbolic links
-----> Using cached Elixir v1.11.2
-----> Installing Elixir v1.11.2 
-----> Installing Hex
/app/.platform_tools/elixir/bin/elixir: 230: exec: erl: Too many levels of symbolic links
-----> Installing rebar
/app/.platform_tools/elixir/bin/elixir: 230: exec: erl: Too many levels of symbolic links
-----> Fetching app dependencies with mix
/app/.platform_tools/elixir/bin/elixir: 230: exec: erl: Too many levels of symbolic links
```

**Comment by jesseshieh** [comment] 2020-11-25 16:46
I haven't investigated yet, but my guess is this was caused by a recent pull request which I just reverted.
https://github.com/HashNuke/heroku-buildpack-elixir/pull/184

Is it still happening now after the revert?

**Comment by philipbrown** [comment] 2020-11-25 17:00
That still didn't seem to work for me. I'm currently using https://github.com/HashNuke/heroku-buildpack-elixir.git#028423beaf0e9d9419a9ff4cfbedd58a2452953c

**Comment by jesseshieh** [comment] 2020-11-25 17:24
Oh hm, can you try clearing your cache and see if that helps? Are you on Heroku or Gigalixir?

**Comment by jesseshieh** [comment] 2020-11-26 00:49
I just tried to reproduce this by using the same elixir, erlang, and stack versions, but had no success. Were you able to get around this by clearing the cache? I'm going to revert the revert from earlier. Let me know if this happens again.

**Comment by philipbrown** [comment] 2020-11-26 08:42
I'm using Heroku. I've just tried the following, all without cache:

- 7ee1d78b2387c75c1d58dc9538d573808347eb5b (worked)
- 503e48fbb9435f42df1068227dbb5b1c02ed62dc (didn't work)
- ea8dc3370f51b7a2aff346b5b132e0a5a7250523 (didn't work)

Let me know if you need me to test anything!

**Comment by jackcarlisle** [comment] 2020-11-26 14:56
Hi there, we're experiencing the same issue on Heroku using the following versions:

```
  * Stack heroku-18
  * Erlang 23.1.2
  * Elixir v1.11.2 
```

**Comment by jesseshieh** [comment] 2020-11-26 16:40
@philipbrown thanks for investigating. I've rolled back the code to match 7ee1d78 with https://github.com/HashNuke/heroku-buildpack-elixir/pull/187

@jackcarlisle thanks for the bug report. Does it still happen now with a clean cache now that I've reverted the change I merged last night?

**Comment by jesseshieh** [comment] 2020-11-26 18:21
@philipbrown @jackcarlisle are either of your apps open source by chance? I can't seem to reproduce this with any of my repos.

**Comment by jackcarlisle** [comment] 2020-11-27 08:44
@jesseshieh that's working for us now, thank you! Unfortunately our app isn't open source but I'm more than happy to share any config that you think might help in solving this

**Comment by jesseshieh** [comment] 2020-11-28 19:32
Thanks @jackcarlisle! That would be really helpful.

-  Do you mind pasting your elixir_buildpack.config so I can see if there's anything interesting in there?
- Also, are you using any other buildpacks besides this one? 
- It would help to have the full git push output when you see the error if you have it. You should be able to reproduce this by setting your buildpack to https://github.com/HashNuke/heroku-buildpack-elixir#503e48fbb9435f42df1068227dbb5b1c02ed62dc

**Closed** 2020-12-10 22:07 UTC
