### ISSUE TITLE
Elixir 1.4.5 build fails

### ISSUE THREAD

**Issue by balexand** [HashNuke/heroku-buildpack-elixir#112] opened 2017-06-24 10:27 UTC
I believe the cause is that Elixir cannot be downloaded from  https://s3.amazonaws.com/s3.hex.pm/builds/elixir/v1.4.5.zip (response is a 403 forbidden error with XML content). Who is responsible for uploading these packages? 

```
remote: -----> Fetching Elixir v1.4.5
remote: -----> Installing Elixir v1.4.5 (changed)
remote: [/app/tmp/cache/elixir-v1.4.5.zip]
remote:   End-of-central-directory signature not found.  Either this file is not
remote:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
remote:   latter case the central directory and zipfile comment will be found on
remote:   the last disk(s) of this archive.
remote: unzip:  cannot find zipfile directory in one of /app/tmp/cache/elixir-v1.4.5.zip or
remote:         /app/tmp/cache/elixir-v1.4.5.zip.zip, and cannot find /app/tmp/cache/elixir-v1.4.5.zip.ZIP, period.
remote: chmod: cannot access ‘/tmp/build_55d98dfe4a0f762b916a2fe1ccdad0fb/.platform_tools/elixir/bin/*’: No such file or directory
remote: -----> Installing Hex
remote: /app/tmp/buildpacks/7dbb5567c3a8b869f9516cd869ebf95082d7cf78f12fea9cba8fad1e1923c580f31b53ba792ed7279cc47894e95fe878ef82661603023bf1f6a023e7c7953587/lib/elixir_funcs.sh: line 87: mix: command not found
remote: -----> Installing rebar
remote: /app/tmp/buildpacks/7dbb5567c3a8b869f9516cd869ebf95082d7cf78f12fea9cba8fad1e1923c580f31b53ba792ed7279cc47894e95fe878ef82661603023bf1f6a023e7c7953587/lib/elixir_funcs.sh: line 93: mix: command not found
remote: -----> Fetching app dependencies with mix
remote: /app/tmp/buildpacks/7dbb5567c3a8b869f9516cd869ebf95082d7cf78f12fea9cba8fad1e1923c580f31b53ba792ed7279cc47894e95fe878ef82661603023bf1f6a023e7c7953587/lib/app_funcs.sh: line 47: mix: command not found
remote:  !     Push rejected, failed to compile Elixir app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to 
```

**Comment by ericmj** [comment] 2017-06-24 11:33
It was a disk space issue on the build server. It has been fixed now.

**Closed by ericmj** 2017-06-24 11:33 UTC

**Comment by SimonWoolf** [comment] 2018-03-02 10:21
@ericmj you're probably already aware of this, but in case you aren't, this issue has been happening again since around 10:44 AM UTC yesterday (March 1st)

**Comment by ericmj** [comment] 2018-03-02 10:22
@SimonWoolf Can you show the error you are getting? Is it possible you are using an old version of the buildpack that is using the old https://s3.amazonaws.com/s3.hex.pm URL instead of the new https://repo.hex.pm?

**Comment by SimonWoolf** [comment] 2018-03-02 10:27
Hi Eric --- thanks for the quick reply! The error doesn't show the url, but is:
```
=====> 10:16:27.863 creating build and cache dirs
=====> 10:16:27.867 exporting buildpack vars
=====> 10:16:27.874 copying app files to build dir
=====> 10:16:30.531 detecting buildpack
=====> 10:16:30.545 elixir app detected
=====> 10:16:30.546 compiling app
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack cedar-14
       * Erlang 19.3
       * Elixir 1.4.5 
       * Runtime path /app
       * Build path /tmp/tmp.GLkG7xxDQz/build
       * Cache path /cache
       * Mix backup path /cache/.mix
       * HOME /app
       Will export the following config vars:
       * Config vars DATABASE_URL
       * MIX_ENV=prod
-----> Stack changed, will rebuild
-----> Cleaning all cache to force rebuilds
-----> Fetching Erlang 19.3

-----> Installing Erlang 19.3 (changed)

-----> Fetching Elixir v1.4.5

-----> Installing Elixir v1.4.5 (changed)
[/cache/elixir-v1.4.5.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /cache/elixir-v1.4.5.zip or
        /cache/elixir-v1.4.5.zip.zip, and cannot find /cache/elixir-v1.4.5.zip.ZIP, period.
chmod: cannot access '/tmp/tmp.GLkG7xxDQz/build/.platform_tools/elixir/bin/*': No such file or directory
```
Re buildpack version: it's possible, sure; I'll find out what sha we're using and update it to the latest version, and let you know whether that fixes it.

**Comment by SimonWoolf** [comment] 2018-03-02 13:14
I can confirm that updating to the latest buildpack version (and rebuilding our slug-builder image) fixes my issue, sorry for the noise.
